# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b3470db653728a0782fa996f8210c2ef326a33fcd10e5723d1240e660c2edbce30d5b30b840b29cea72aaac88fddb6285919a40b66c0e5a89ffebb41facfe2
  google_client_id: 394199946398-cnvjl3claj3fb8scaccmuagfcqpo4dk5.apps.googleusercontent.com
  google_client_secret: 2C0OuE574D5c-Y0n1yphghqg

test:
  secret_key_base: 6a87b796143afbefea0889b056cb4be0154b993e74bc883a8e6f80acf90fab382079bc54a57be8818a21567d1a32d80ee49c86cac5158ab046b99d9260b287f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
